### ISSUE TITLE
[BUG] Devices should not be created for virtual network entries created by docker.

### ISSUE THREAD

**Issue by zelch** [joshuar/go-hass-agent#573]
**Go Hass Agent Version**
v13.3.0-dirty

**Describe the bug**
When I noticed the problem, I had over 10,000 entities in home assistant, with naming of veth*, br-*, or the like.

**To Reproduce**
Have a workflow that involves bringing up and down docker compose instances with network segments between the containers, while running go-hass-agent.

**Expected behavior**
Excluding virtual devices would be ideal, but at a minimum _something_ should notice when there are over a thousand entities. :)
**Desktop (please complete the following information):**

- OS: Linux
- Distribution: Ubuntu
- Version: 25.04

**Additional context**

**Comment by joshuar** [comment]
Hey there, thanks for reporting this issue and oh dear indeed, that is not good! I just checked on my home server and indeed, I have a similar situation, ugh...

I've just released [v13.3.3](https://github.com/joshuar/go-hass-agent/releases/tag/v13.3.3) which should fix the issue. Please do try it out!

It should be possible to also add any additional devices you want to ignore by adding them to the `ignored_devices` settings under the `[sensors.network]` sections in the preferences file (usually located at `~/.config/go-hass-agent/preferences.toml`). It works on prefix matches, so something like `eth` would ignore all devices such as `eth0`, `eth1`, etc.

I really need to clean up the preferences, it's a bit clunky to have to do this in multiple places, I'll add it to my todos.

**Comment by rfdrake** [comment]
I really wish homeassistant would have builtin thresholds for entities and give a warning in the logs if something is higher than reasonable.  I had the same issue and spent a couple of days troubleshooting because the only obvious clue was a very slow web interface.  I had around 100,000 entities and the auto-entities plugin just wasn't made to handle that. I think the built-in cards were coping with it better though, so HA might not want to consider this an issue even though it seems bad. Surely there are other things out there which could create thousands of entities automatically.

After fixing this I decided to keep track of my entities in a homeassistant card so that I know if they're getting out of control. If you're interested in this, you might create these as custom sensors rather than template-entity-rows.  That way you can setup automation to alert you if something goes higher than xxx.

```
type: entities
entities:
  - type: custom:template-entity-row
    name: "Sensors:"
    state: "{{ states.sensor | count }}"
  - type: custom:template-entity-row
    name: "Lights:"
    state: "{{ states.light | count }}"
  - type: custom:template-entity-row
    name: "Switches:"
    state: "{{ states.switch | count }}"
  - type: custom:template-entity-row
    name: "Binary Sensors:"
    state: "{{ states.binary_sensor | count }}"
  - type: custom:template-entity-row
    name: "Automations:"
    state: "{{ states.automation | count }}"
  - type: custom:template-entity-row
    name: "Cameras:"
    state: "{{ states.camera | count }}"
  - type: custom:template-entity-row
    name: "Total Entities Count:"
    state: "{{ states | map(attribute='entity_id') | list | count }}"
title: Home Assistant
```

**Comment by ClearlyDazed** [comment]
@joshuar I was wondering if on a headless server (ubuntu 24.04) using systemd to load v13.3.3 of go hass agent, a config file was available to ignore devices.

Under the server user login I found the preference.toml file to allow this. Thanks for developing this program

**Comment by pschmitt** [comment]
I still see veth sensors, even though i have this in the config (which is present by default):

```toml
  [sensors.network]

    [sensors.network.connections]
      disabled = false
      ignored_devices = ["veth", "podman", "docker"]

    [sensors.network.links]
      disabled = false
      ignored_devices = ["veth", "podman", "docker"]

    [sensors.network.usage]
      disabled = false
      ignored_devices = ["veth", "podman", "docker"]
      update_interval = "5s"
```

Sensors:

```
» hass-cli state list 'sensor..*veth.*'
ENTITY                             DESCRIPTION                 STATE    CHANGED
sensor.ge2_vethdc7471e_link_state  ge2 vethdc7471e Link State  up       2025-09-26T09:16:55.123473+00:00
sensor.ge2_veth7902f96_link_state  ge2 veth7902f96 Link State  up       2025-09-26T09:16:57.559300+00:00
sensor.ge2_vetha9d890c_link_state  ge2 vetha9d890c Link State  up       2025-09-26T09:16:58.020483+00:00
sensor.ge2_veth55765bd_link_state  ge2 veth55765bd Link State  up       2025-09-26T09:16:58.378478+00:00
sensor.ge2_veth79a5321_link_state  ge2 veth79a5321 Link State  up       2025-09-26T09:16:58.734597+00:00
sensor.ge2_vethc8a5c7e_link_state  ge2 vethc8a5c7e Link State  up       2025-09-26T09:16:59.798174+00:00
sensor.ge2_vetha25e8c1_link_state  ge2 vetha25e8c1 Link State  up       2025-09-26T09:17:00.528668+00:00
sensor.ge2_veth9aa3b36_link_state  ge2 veth9aa3b36 Link State  up       2025-09-26T09:17:01.001634+00:00
sensor.ge2_veth15c111f_link_state  ge2 veth15c111f Link State  up       2025-09-26T09:17:03.914781+00:00
sensor.ge2_veth593f76c_link_state  ge2 veth593f76c Link State  up       2025-09-26T09:17:04.328366+00:00
sensor.ge2_vethcdfa056_link_state  ge2 vethcdfa056 Link State  up       2025-09-26T09:17:04.732415+00:00
sensor.ge2_vethe1cd584_link_state  ge2 vethe1cd584 Link State  up       2025-09-26T09:17:05.899855+00:00
sensor.ge2_veth57ed85f_link_state  ge2 veth57ed85f Link State  up       2025-09-26T09:17:06.324442+00:00
sensor.ge2_vethc29934a_link_state  ge2 vethc29934a Link State  up       2025-09-26T09:17:06.713187+00:00
sensor.ge2_vethc6f3194_link_state  ge2 vethc6f3194 Link State  up       2025-09-26T09:17:07.536714+00:00
sensor.ge2_veth63e80dc_link_state  ge2 veth63e80dc Link State  up       2025-09-26T09:17:09.023803+00:00
sensor.ge2_veth6815bf2_link_state  ge2 veth6815bf2 Link State  down     2025-09-26T09:17:14.932898+00:00
sensor.ge2_veth50ff592_link_state  ge2 veth50ff592 Link State  down     2025-09-26T09:17:15.745713+00:00
sensor.ge2_veth220e331_link_state  ge2 veth220e331 Link State  down     2025-09-26T09:17:32.260788+00:00
sensor.ge2_vethb1e9dc4_link_state  ge2 vethb1e9dc4 Link State  down     2025-09-26T09:17:32.900465+00:00
sensor.ge2_vethe1d17a6_link_state  ge2 vethe1d17a6 Link State  down     2025-09-26T09:18:30.864380+00:00
sensor.ge2_vethb40a7c0_link_state  ge2 vethb40a7c0 Link State  down     2025-09-26T09:18:31.305259+00:00
sensor.ge2_veth86d0b5d_link_state  ge2 veth86d0b5d Link State  down     2025-09-26T09:19:29.725010+00:00
sensor.ge2_veth7ae8653_link_state  ge2 veth7ae8653 Link State  down     2025-09-26T09:19:30.227978+00:00
sensor.ge2_vethaf50f74_link_state  ge2 vethaf50f74 Link State  down     2025-09-26T09:20:29.974476+00:00
sensor.ge2_vethc76a9fa_link_state  ge2 vethc76a9fa Link State  down     2025-09-26T09:20:30.680053+00:00
sensor.ge2_vethff0772e_link_state  ge2 vethff0772e Link State  down     2025-09-26T09:21:30.166742+00:00
sensor.ge2_veth5e115fe_link_state  ge2 veth5e115fe Link State  down     2025-09-26T09:21:30.551101+00:00
sensor.ge2_veth043a05b_link_state  ge2 veth043a05b Link State  down     2025-09-26T09:22:29.660483+00:00
sensor.ge2_vethc2c503c_link_state  ge2 vethc2c503c Link State  down     2025-09-26T09:22:30.877565+00:00
```

**Comment by joshuar** [comment]
Hey there, this should be fixed in [v14](https://github.com/joshuar/go-hass-agent/releases/tag/v14.0.2). The link state sensor code was not using the values in the preferences 😿 Please try it out when you get a chance and report back! Cheers!

**Comment by pschmitt** [comment]
erm this is definitely still happening with 14.0.2.

**Comment by pschmitt** [comment]
and fixed with 14.0.3! Thanks.

**Comment by hobbypunk90** [comment]
@pschmitt sorry, but still happening for devices with a dash in it 😅 
i'm running the go-hass-agent docker image on my nas, veth don't show up, but every br-... device.
precerences.toml:
```
[sensors.network]
[sensors.network.connections]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']

[sensors.network.links]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']

[sensors.network.usage]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']
update_interval = '15s'

```

<img width="257" height="321" alt="Image" src="https://github.com/user-attachments/assets/bc9d7c50-c35c-4006-82c4-bd08154acf5f" />

**Comment by joshuar** [comment]
Oh dear, that's no good. The code filters by doing a string prefix match (case-sensitive). I'm assuming these bridge devices are standard bridge devices and all start with `br` when you run, `ip link show`?

**Comment by joshuar** [comment]
Hmm, I'm having trouble reproducing this issue.

I created a dummy device with:

```shell
sudo ip link add br-fake type dummy
sudo ip address add 10.0.0.1/24 dev br-fake
sudo ip link set br-fake up
```

When I then set the following ignored_devices:

```toml
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'br']
```

No entities get created for the `br-fake` device. Taking it out of the list causes the agent to generate entities as expected.

I'm really unsure why the other prefix matches would work and then **specifically** not work for a device that starts with `br`.

Can you try running the agent with the option `--log-level=debug` and seeing if there are any messages at any level that mention "netlink" or "network" or specifically the br device names?

**Comment by hobbypunk90** [comment]
`ip link show` :
```
1007: br-39b33ef3c1ae: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:e2:80:6b:06 brd ff:ff:ff:ff:ff:ff
...
```
looking like default br devices 😅 

i checked with log level debug:

```
2025-10-11 12:03:20.233153+00:0012:03PM DEBUG Sensor not found in registry. sensor_id=br-4ebb4d7aa786_bytes_received
2025-10-11 12:03:20.299946+00:0012:03PM DEBUG Sensor registered. hass.sensor.name="br-4ebb4d7aa786 Bytes Received" hass.sensor.id=br-4ebb4d7aa786_bytes_received hass.sensor.state="792 B"
2025-10-11 12:03:20.393663+00:0012:03PM DEBUG Sensor not found in registry. sensor_id=br-4ebb4d7aa786_bytes_sent
2025-10-11 12:03:20.451968+00:0012:03PM DEBUG Sensor registered. hass.sensor.name="br-4ebb4d7aa786 Bytes Sent" hass.sensor.id=br-4ebb4d7aa786_bytes_sent hass.sensor.state="42950 B"
2025-10-11 12:03:20.563192+00:0012:03PM DEBUG Sensor not found in registry. sensor_id=br-4ebb4d7aa786_bytes_received_throughput
2025-10-11 12:03:20.655490+00:0012:03PM DEBUG Sensor registered. hass.sensor.name="br-4ebb4d7aa786 Bytes Received Throughput" hass.sensor.id=br-4ebb4d7aa786_bytes_received_throughput hass.sensor.state="0 B/s"
2025-10-11 12:03:20.931203+00:0012:03PM DEBUG Sensor not found in registry. sensor_id=br-4ebb4d7aa786_bytes_sent_throughput
2025-10-11 12:03:21.197058+00:0012:03PM DEBUG Sensor registered. hass.sensor.name="br-4ebb4d7aa786 Bytes Sent Throughput" hass.sensor.id=br-4ebb4d7aa786_bytes_sent_throughput hass.sensor.state="0 B/s"
```

with this settings in my preferences.toml:
```
[sensors.network]
[sensors.network.connections]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']

[sensors.network.links]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']

[sensors.network.usage]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']
update_interval = '15s'
```

When we found the problem, will go-hass-agent delete the sensors automatically?

**Comment by pschmitt** [comment]
I don't believe home assistant companions can remove sensors once they are registered. Have you tried re-registering?

**Comment by joshuar** [comment]
Yeah unfortunately, there is no way for the agent to remove entities once they've been registered with Home Assistant. Though in recent versions, Home Assistant does seem to detect when the agent is no longer updating the sensor and offer to remove it.

As @pschmitt suggested, you can try re-registering. I need to update the docs but the gist is:

1. Shut down Go Hass Agent.
2. Remove the Agent instance from Home Assistant under the mobile app integration.
3. Copy the `server` and `token` values under the **registration** section of the agent preferences file. (Usually `~/.config/go-hass-agent/preferences.toml`). Don't delete the file or config directory (not needed).
4. Run a forced registration in a terminal with:
  ```shell
go-hass-agent register --server _SERVER_ --token _TOKEN_ --force
  ```
5. Agent should report successful registration.
6. Restart agent.

Keeping the agent config file ensures the agent registers with the same device ID and so to Home Assistant, looks like the same mobile app (and thus keeps all your long term history stats).

Please do try re-registering and see if that either removes the unwanted entities.

**Comment by rfdrake** [comment]
I've had the same issue but didn't notice for a while. I just looked again and had 15000 entities registered to my host.

I've tried a few options. I originally had disabled = true and ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet',  'br'] but I thought they might conflict with each other, so now I have only "disabled = true" on all network options.

I've tried to fully disable network interfaces for go-hass-agent:

```
[sensors.network]
disabled = true

[sensors.network.connections]
disabled = true

[sensors.network.links]
disabled = true

[sensors.network.usage]
disabled = true
```

Here is what I see in homeassistant (using hass-cli) after re-registering.

```
sensor.host_eno6np1_link_state                                                   host eno6np1 Link State                                                    down                              2025-10-13T21:38:42.074562+00:00
sensor.host_eno1_link_state                                                      host eno1 Link State                                                       up                                2025-10-13T21:38:42.400617+00:00
sensor.host_eno5np0_link_state                                                   host eno5np0 Link State                                                    down                              2025-10-13T21:38:42.477631+00:00
... (several more physical and virtual interfaces omitted)
```

One more thought:  Should I remove the sensorRegistry while re-registering? I'd rather not do that because I'm guessing it'll rewrite the entity IDs, but I wonder if the agent is using that as a reference for what to send to homeassistant?

**Comment by pschmitt** [comment]
If I were you, I would:

1. delete the device from Home Assistant
2. Stop go-hass-agent
3. `rm -rf ~/.config/go-hass-agent`
4. Start the go-hass-agent service again

**Comment by hobbypunk90** [comment]
@joshuar sorry for the delay, i tested it recently with the new version 14.1.1. same problem
```toml
[sensors.network]
[sensors.network.connections]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']

[sensors.network.links]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']

[sensors.network.usage]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']
update_interval = '15s'
```

but

<img width="282" height="504" alt="Image" src="https://github.com/user-attachments/assets/4dd25cc8-458f-482c-84d2-75bf06c2524c" />

there are instant over 200 entities 😒  before i deleted it, they grow to over 800 😢 

```
5:58AM DEBUG Sensor not found in registry. sensor_id=br-d28c14153c4a_bytes_sent
5:58AM DEBUG Sensor registered. hass.sensor.name="br-d28c14153c4a Bytes Sent" hass.sensor.id=br-d28c14153c4a_bytes_sent hass.sensor.state="3.2652283e+07 B"
5:58AM DEBUG Sensor not found in registry. sensor_id=br-d28c14153c4a_bytes_received_throughput
5:58AM DEBUG Sensor registered. hass.sensor.name="br-d28c14153c4a Bytes Received Throughput" hass.sensor.id=br-d28c14153c4a_bytes_received_throughput hass.sensor.state="0 B/s"
5:58AM DEBUG Sensor not found in registry. sensor_id=br-d28c14153c4a_bytes_sent_throughput
5:58AM DEBUG Sensor registered. hass.sensor.name="br-d28c14153c4a Bytes Sent Throughput" hass.sensor.id=br-d28c14153c4a_bytes_sent_throughput hass.sensor.state="0 B/s"
5:58AM DEBUG Sensor not found in registry. sensor_id=br-ede090cd79de_bytes_received
```

edit:
i thought i found my problem by missing the this config block:
```toml
[sensors.network.rates]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet', 'incusbr0', 'br']
```
i added it, deleted my device, reset the registration, no changes 😢

**Comment by joshuar** [comment]
Hey folks, in my testing the latest versions correctly ignore devices configured in your preferences file.

For those of you stuck with lots of unwanted entries. Can you please follow the [reset the agent](https://github.com/joshuar/go-hass-agent/?tab=readme-ov-file#can-i-reset-the-agent-start-from-new) instructions in the faq explicitly?

1. Stop the agent on the device.
2. Delete the entry for the agent in the Mobile App integration in Home Assistant.
3. **Do not manually delete/recreate the agent configuration directory or preference file on the device.**
4. Force-register the agent on the device with the command `go-hass-agent register --force --server _server_ --token _token_` (you can grab the _server_ and _token_ values from the saved preference file.
5. Restart the agent on the device.

In my testing, following the reset procedure in the FAQ (and above) with an existing preferences file with your desired ignored_devices set will correctly remove any devices that should be ignored.

Following the procedure above will ensure that the device ID remains the same, keeping long-term statistics. If you manually delete the preferences file, the agent generates a new ID for itself when registering and you may lose your long-term statistics.

I hope that works out 🤞

Cheers!

**Comment by hobbypunk90** [comment]
hey @joshuar,

i recently test it.
Before reset there was nearly 400 entities. i reseted as you described. now there are slightly below 100 entities and nothing a wanna ignore. 
it seams to work 🥳

Greets,
Marcel

**Comment by joshuar** [comment]
Hey folks I'm going to close this issue on the assumption its finally fixed (phew!) If you are using the latest version and it still isn't working, and following the reset steps in https://github.com/joshuar/go-hass-agent/issues/573#issuecomment-3797871830 don't work, please re-open and we can continue to troubleshoot. 

Cheers!
